[package]
name = "ark-sa-server-manage-bot"
version = "0.1.0"
authors = ["Daisuke Yamamura <mucho613@gmail.com>"]
edition = "2024"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
toml = "0.8.23"
